-- Mapper에 들어갈 query
-- Book.xml id= mainList (신작 순서대로 book 리스트 출력)
SELECT * FROM BOOK ORDER BY BRDATE DESC;

-- BOOK.XML ID = BOOKLIST (책이름 가나다순, BOOK리스트 탑앤구문)
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOOK ORDER BY BTITLE) A) WHERE RN BETWEEN 2 AND 4;

-- BOOK.XML ID = TOTCNTBOOK
SELECT COUNT(*) FROM BOOK;

-- BOOK.XML ID = GETDETAILBOOK
SELECT * FROM BOOK WHERE BNUM = 2;

--BOOK.XML ID = REGISTERBOOK
INSERT INTO BOOK (BNUM, BTITLE, BWRITER, BRDATE, BIMG1, BIMG2, BINFO)
VALUES (BOOK_SQ.NEXTVAL, 'JAVASCRIPT', '장자바', '23/10/09', 'noimg.png', 'noimg.png', '자바스크립트 개념서');

-- BOOK.XML ID = MODIFYBOOK
UPDATE BOOK SET BTITLE= 'Javascript', BWRITER= '최자바', BIMG1= 'noimg.png', BIMG2='noimg.png', BINFO = 'JavaScript 개념서' WHERE BNUM=5;


----
select * from book_member;
-- MEMBER.XML ID = IDCONFIRM (RESULTTYPE=INT)
SELECT COUNT(*) FROM BOOK_MEMBER where mid='aaa';

-- MEMBER.XML ID = JOINMEMBER
INSERT INTO BOOK_MEMBER (MID, MPW, MNAME, MMAIL, MPOST, MADDR)
VALUES ('ccc', 'aaa', '김길동', 'baba@cc.com', '53235', '부산');

-- MEMBER.XML ID = GETDETAILMEMBER
SELECT * FROM BOOK_MEMBER WHERE MID='ccc';

-- MEMBER.XML ID = MODIFYMEMBER
UPDATE BOOK_MEMBER
SET MPW='bbb', MNAME='최길동', MMAIL= 'cc@aaa.com', MPOST=23532, MADDR = '대전'
WHERE MID = 'ccc';
