-- 1. DROP & CREATE 테이블 (FRIEND, NO, NAME, TEL)과 시퀀스 (FRIEND_NO_SEQ 1씩증가)
CREATE SEQUENCE FRIEND_NO_SEQ
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
NO NUMBER(5),
NAME VARCHAR2(30),
TEL VARCHAR2(50)
);

SELECT * FROM FRIEND;

-- 2. DAO에 들어갈 쿼리 (전체친구 출력 / 친구추가)
-- 1) 전체친구출력
SELECT * FROM FRIEND;
commit;


-- 2) 친구추가
INSERT INTO FRIEND (NO, NAME, TEL)
VALUES (FRIEND_NO_SEQ.NEXTVAL, '김김김', '010-252-2525');

-- 3) 친구검색
SELECT * FROM FRIEND WHERE ( NAME LIKE '%'||''||'%' AND TEL LIKE '%'||''||'%' ) OR tel is null;