CREATE TABLE PRODUCT2(
PNO NUMBER(3) PRIMARY KEY,
PNAME VARCHAR2(50) NOT NULL UNIQUE,
PSTOCK NUMBER(3) NOT NULL
);

SELECT * FROM PRODUCT2;

INSERT INTO PRODUCT2 VALUES (1,'공책',3);
INSERT INTO PRODUCT2 VALUES (2, '공책2', 5);
INSERT INTO PRODUCT2 VALUES (3, '지우개', 0);
INSERT INTO PRODUCT2 VALUES (4, '볼펜', 13);
COMMIT;

-- DAO에 들어갈 QUERY
SELECT * FROM PRODUCT2;
SELECT PSTOCK FROM PRODUCT2 WHERE PNAME = '공책';

DROP TABLE PRODUCT2;
select * from MVC_MEMBER;