-- [VIII] - Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SEQ; -- 시퀀스의 이름은 테이블명_SEQ로 만드는 경우가 많음.
CREATE SEQUENCE FRIEND_SEQ
START WITH 1 -- 1부터 시작하는 시퀀스. 안 써도 1부터 시작 (디폴트)
INCREMENT BY 1 -- 1씩 증가. 감소 원하면 -1
MAXVALUE 9999 -- 꼭 설정.
MINVALUE 1 -- 보통 1이지만, INCREMENT가 마이너스일 경우의 최소값을 지정해 주는 것.
NOCACHE -- 컴퓨터가 자동으로 확보하는 값. 시퀀스가 중간에 빠질 수 있으므로, NOCACHE는 꼭 기입할 것.
NOCYCLE; -- 순환X. 9999 다음을 1로 만들지 않음. (중복방지). MAXVALUE, NOCACHE, NOCYCLE은 꼭 기입하자.

CREATE SEQUENCE FRIEND_SEQ
MAXVALUE 9999
MINVALUE 1
NOCACHE
NOCYCLE;

SELECT FRIEND_SEQ.NEXTVAL FROM DUAL;
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; --게시판 만들때 둘다 필요...
DROP SEQUENCE FRIEND_NO_SEQ;

CREATE SEQUENCE FRIEND_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 99999 NOCACHE NOCYCLE;
 -- NO에 들어갈 시퀀스를 생성.
 DROP TABLE FRIEND;
 CREATE TABLE FRIEND (
 NO NUMBER(5) PRIMARY KEY, -- 시퀀스를 넣을 값. MAXVALUE가 99999이므로 NUMBER를 5로.
 NAME VARCHAR2 (30) NOT NULL,
 TEL VARCHAR2 (20) UNIQUE, -- NULL은 허용하나, NULL이 아닌 경우는 유일한 값이어야 함
 ADDRESS VARCHAR2 (255),
LAST_MODIFY DATE DEFAULT SYSDATE 
 );
 
 INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS) 
 VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', NULL, '서울 서대문');
 -- 만일 NO를 숫자 1 등으로 입력하면 1회 이후 생성이 불가. 그러나 NEXTVAL을 사용하면 생성할 때 자동으로 다음 번호가 입력됨.
 SELECT * FROM FRIEND;
 INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
 VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9998', '서울 마포');
 SELECT * FROM FRIEND;
  
 -- EX. 초기값 101부터 최대값 999,999까지 1씩 증가하는 TEST_SEQ 시퀀스를 생성하고 시퀀스를 사용하시오
DROP SEQUENCE TEST_SEQ;
CREATE SEQUENCE TEST_SEQ INCREMENT BY 1 START WITH 101 MAXVALUE 999999 NOCACHE NOCYCLE;
SELECT TEST_SEQ.CURRVAL FROM DUAL; -- 한번도 사용하기 전에는 값을 가져올 수 없음
SELECT TEST_SEQ.NEXTVAL FROM DUAL;

-- EX. 시퀀스 NO_SEQ 초기값 1부터 999까지 
-- SYSDATE의 값을 'RRMMDD'만 추출하고 뒤에 001 ~ 999
DROP SEQUENCE NO_SEQ;
CREATE SEQUENCE NO_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 999 NOCACHE NOCYCLE;
SELECT CONCAT(TO_CHAR(SYSDATE,'RRMMDD'),TRIM(TO_CHAR(NO_SEQ.NEXTVAL,'000'))) NO FROM DUAL; 
-- 띄어쓰기 발생. TO_CHAR와 TO_CHAR를 이으면 뒷쪽 TO_CHAR에 스페이스가 생기므로, TRIM을 사용해서 없애주어야 함.
-- TRIM은 문자 사이에 있는 띄어쓰기가 아닌 문자 바깥에 있는 띄어쓰기를 없애므로 전체를 감싸선 안 됨.

