-- DROP AND CREATE TABLE & SEQUENCE
DROP TABLE BOARD;
DROP SEQUENCE BOARD_SEQ;

CREATE TABLE BOARD(
BID NUMBER(6) PRIMARY KEY,
BNAME VARCHAR2 (50) NOT NULL,
BTITLE VARCHAR2 (100),
BCONTENT CLOB, -- 4천바이트 이상인경우
BEMAIL VARCHAR2(50),
BHIT NUMBER(6) DEFAULT 0 NOT NULL, -- 조회수
BPW VARCHAR2(50) NOT NULL,
BGROUP NUMBER(6) NOT NULL,
BSTEP NUMBER(3) NOT NULL,
BINDENT NUMBER(3) NOT NULL,
BIP VARCHAR2(20) NOT NULL,
BDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE BOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
SELECT * FROM BOARD;

-- 더미데이터
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
VALUES (BOARD_SEQ.NEXTVAL, '홍길동', '냉면', '냉무', 'AA@BB.COM', '111', BOARD_SEQ.CURRVAL,  0, 0, '127.0.0.1' ); -- 이메일까지는 사용자에게 받음. BGROUP, BSTEP, BINDENT는 글 타입에 따라 매겨짐.
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
VALUES (BOARD_SEQ.NEXTVAL, '신성', 'ㅁㅋㅅㄹ', 'ㄹㅇ', 'AA@BB.COM', '111', BOARD_SEQ.CURRVAL,  0, 0, '192.0.0.1' );
SELECT * FROM BOARD;


UPDATE board SET bemail='BB@CC.COM' WHERE BID =2;

-- DAO에 사용할 쿼리문
-- 1) 글목록 (페이징 처리. startrow부터 endrow까지의 리스트)
SELECT * FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC) ORDER BY BID DESC;
SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC) A;
SELECT *
FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC) A)
WHERE RN BETWEEN 41 AND 50;

-- 2) 전체 글 갯수
SELECT COUNT(*) CNT FROM BOARD;

-- 3) 원글쓰기 -- 작성자, 글제목, 본문, 이메일, 비밀번호, IP(FROM JAVA) 를 사용자에게 받아 게시글을 등록. (BGROUP은 글번호, BSTEP은 0, BINDENT는 0)
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
VALUES (BOARD_SEQ.NEXTVAL, '신성', 'ㅂㄱ', 'ㄹㅇ', 'AA@BB.COM', '111', BOARD_SEQ.CURRVAL,  0, 0, '192.0.0.1' );

-- 4) 글보기 - 조회수올리기 (BID 이용)
UPDATE BOARD SET BHIT = BHIT+1 WHERE BID = 1;
-- 5) 글보기 - 게시글 상세보기 (DTO 가져오기).. 4와 5를 함께 사용

-- 6) 글수정/답변글 - BID로 DTO 가져오기 (글수정FORM, 답변글FORM 이용시 사용), 조회수 올리기 사용 X
SELECT * FROM BOARD WHERE BID = 1;
-- 7) 글수정 (작성자, 글제목, 본문, 이메일, 비밀번호 수정가능)
UPDATE BOARD
SET BNAME = '홍스길스동스',
BTITLE = '바꾼제목',
BCONTENT = '바꾼본문',
BEMAIL = 'H@H.COM',
BPW = '111',
BIP = '127.0.0.1'
WHERE BID = 1;
COMMIT;
--8) 글삭제 (비밀번호를 맞게 입력한 경우에만 삭제됨)
DELETE FROM BOARD WHERE BID = 1 AND BPW = '111';
commit;
ROLLBACK;
SELECT * FROM BOARD ORDER BY BGROUP DESC;
DELETE FROM BOARD WHERE BNAME = '홍길동동' AND BID != 16;

--9 ) 답변쿼리

-- 원글
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
VALUES (BOARD_SEQ.NEXTVAL, '박','글3','냉무','AA@BB.COM','111',BOARD_SEQ.CURRVAL, 0, 0, '127.0.0.1');
SELECT * FROM BOARD;

-- 답변글 쓸 때에는 BSTEP을 조정해주어야함. 원글(BSTEP=0)을 제외하고.
UPDATE BOARD SET BSTEP = BSTEP+1 WHERE BGROUP = 3 AND BSTEP >0; -- 3번째 게시글 중 BSTEP은 0보다 큰 (댓글인) 것들의 BSTEP을 +1해줌.
SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP;

-- 답변글 INSERT
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
VALUES (BOARD_SEQ.NEXTVAL, '윤','글3-1','냉무맞음','DFDS@CC.COM','111',(SELECT BGROUP FROM BOARD WHERE BGROUP = 8), 1, 1, '127.0.0.1');

COMMIT;
ROLLBACK;

-- 글 2-1
-- A단계 (BSTEP조정)
UPDATE BOARD SET BSTEP = BSTEP+1 WHERE BGROUP=7 AND BSTEP >0;
-- 답변글 INSERT
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
VALUES (BOARD_SEQ.NEXTVAL, '징기','ㅂㄱ-2','냉무맞나','DF@CC.COM','111',(SELECT BGROUP FROM BOARD WHERE BGROUP = 7), 1, 1, '127.0.0.1');

-- 글 2-2
UPDATE BOARD SET BSTEP = BSTEP+1 WHERE BGROUP=7 AND BSTEP >0;

INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
VALUES (BOARD_SEQ.NEXTVAL, '신성','좀가-3','냉무맞음','DFS@CC.COM','111',7, 1, 1, '127.0.0.1');

UPDATE BOARD SET BTITLE='ㅂㄱ(원글)' WHERE BID=7;

-- 답변글 3의 답변글 (답답글INSERT)
SELECT * FROM BOARD WHERE BID = 7; -- 원글정보 (BGROUP, BSTEP, BINDENT)
UPDATE BOARD SET BSTEP = BSTEP+1 WHERE BGROUP=7 AND BSTEP >1; -- 답변의 답변이므로 BSTEP은 답변글보다 커야함.
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
VALUES (BOARD_SEQ.NEXTVAL, '주인','조용히하세요-4','냉무맞음','DFS@CC.COM','111',7, 2, 2, '127.0.0.1');


-- RESET

--DAO에 들어갈 쿼리

-- 1. 글목록에서 ORDER BY 부분 추가. BSTEP이 ORDER BY에 추가되었음.
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP) A)
WHERE RN BETWEEN 2 AND 4;

--REPLY 전 BSTEP 조정 (답변글 쓰기 전 BSTEP 조정- 답글이 없는 경우엔 변동 없음, 답변글이 있는 경우 해당 답변글들이 BSTEP+1됨)
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
VALUES (BOARD_SEQ.NEXTVAL, '주인','조용히하세요-4','냉무맞음','DFS@CC.COM','111',7, 2, 2, '127.0.0.1');