-- Emp.xml의 id = empList

SELECT * FROM EMP ORDER BY EMPNO;
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM EMP ORDER BY EMPNO) A) WHERE RN BETWEEN 6 AND 10;


-- 출력기준
SELECT * FROM EMP E, DEPT D WHERE D.DEPTNO= E.DEPTNO ORDER BY EMPNO;
SELECT * FROM (SELECT ROWNUM RN, A.*
FROM (SELECT E.*, DNAME, LOC FROM EMP E, DEPT D WHERE D.DEPTNO=E.DEPTNO ORDER BY EMPNO) A)
WHERE RN BETWEEN 6 AND 10;

-- EMP.XML의 ID =totCnt
SELECT COUNT(*) FROM EMP;

-- EXP.XML의 ID= detail
SELECT * FROM EMP WHERE EMPNO= 7369;

-- EMP.XML의 ID= managerList 매니저인 사람만.
SELECT * FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP);

-- EMP.XML의 ID = insert
INSERT INTO EMP VALUES (9001, '홍길동', ',MANAGER', '7902', SYSDATE, 500,100, 40);

-- EMP.XML의 ID= update
UPDATE EMP SET 
ENAME = '신길동',
JOB = 'SALESMAN',
MGR = 7902,
HIREDATE = '23/11/01',
SAL = 3000,
COMM = 0,
DEPTNO = 30
WHERE EMPNO = 9001;

-- EMP.XML의 id = delete
DELETE FROM EMP WHERE EMPNO = 9000;


-- DEPT.XML의 ID= deptList
SELECT * FROM DEPT;
select * from emp;





