-- DML 데이터 (select...)
-- 1번. 사용자에게 PNAME, JNAME, KOR, ENG, MAT 입력받아 PERSON에 INSERT
SELECT JNAME FROM JOB;
INSERT INTO PERSON VALUES
(PERSON_PNO_SEQ.NEXTVAL, (SELECT JNO FROM JOB WHERE JNAME = ?), ?,?,?,?);


SELECT JNAME FROM JOB; --사용자에게 어떤 직업이 있는지 보여줌
INSERT INTO PERSON VALUES 
(PERSON_PNO_SEQ.NEXTVAL, (SELECT JNO FROM JOB WHERE JNAME = '배우'), '홍길동', 99, 99, 100);
rollback;

-- 2번 기능. JNAME을 입력받아, 등수, 이름 PNAME(PNO), JNAME, KOR, ENG, MAT, SUM 출력
SELECT * FROM PERSON;
SELECT PNAME||'('||PNO||')' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM FROM PERSON, JOB WHERE PERSON.JNO=JOB.JNO ORDER BY SUM DESC;

SELECT ROWNUM RANK, A.* 
FROM (SELECT PNAME||'('||PNO||')' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM FROM PERSON, JOB WHERE PERSON.JNO=JOB.JNO AND 
JNAME= '배우' ORDER BY SUM DESC) A;

-- 3번 기능. 모든 PERSON을 랭크별로 출력. (2번에서 WHERE쿼리만 없애면됨
SELECT ROWNUM RANK, A.* 
FROM (SELECT PNAME||'('||PNO||')' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM FROM PERSON, JOB WHERE PERSON.JNO=JOB.JNO ORDER BY SUM DESC) A;
select * from person;
delete from person where pname = '홍길동';
commit;