SELECT A.EMPNO, A.ENAME, NVL(B.ENAME,'-CEO-') SANGSA, A.MGR, A.SAL, GRADE
FROM EMP A, EMP B, DEPT D, SALGRADE 
WHERE A.SAL BETWEEN LOSAL AND HISAL 
AND A.MGR=B.EMPNO(+) 
AND A.DEPTNO = D.DEPTNO
AND DNAME = UPPER('accounting') ORDER BY SAL DESC;

select * from dept;