-- DROP AND CREATE TABLE & SEQUENCE
DROP TABLE BOARD;
DROP SEQUENCE BOARD_SEQ;

CREATE TABLE BOARD(
BID NUMBER(6) PRIMARY KEY,
BNAME VARCHAR2 (50) NOT NULL,
BTITLE VARCHAR2 (100),
BCONTENT CLOB, -- 4천바이트 이상인경우
BEMAIL VARCHAR2(50),
BHIT NUMBER(6) DEFAULT 0 NOT NULL, -- 조회수
BPW VARCHAR2(50) NOT NULL,
BGROUP NUMBER(6) NOT NULL,
BSTEP NUMBER(3) NOT NULL,
BINDENT NUMBER(3) NOT NULL,
BIP VARCHAR2(20) NOT NULL,
BDATE DATE DEFAULT SYSDATE NOT NULL
);

SELECT * FROM BOARD;