-- DROP AND CREATE TABLE & SEQUENCE
DROP TABLE BOARD;
DROP SEQUENCE BOARD_SEQ;

CREATE TABLE BOARD(
BID NUMBER(6) PRIMARY KEY,
BNAME VARCHAR2 (50) NOT NULL,
BTITLE VARCHAR2 (100),
BCONTENT CLOB, -- 4천바이트 이상인경우
BEMAIL VARCHAR2(50),
BHIT NUMBER(6) DEFAULT 0 NOT NULL, -- 조회수
BPW VARCHAR2(50) NOT NULL,
BGROUP NUMBER(6) NOT NULL,
BSTEP NUMBER(3) NOT NULL,
BINDENT NUMBER(3) NOT NULL,
BIP VARCHAR2(20) NOT NULL,
BDATE DATE DEFAULT SYSDATE NOT NULL
);
CREATE SEQUENCE BOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
SELECT * FROM BOARD;

-- 더미데이터
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
VALUES (BOARD_SEQ.NEXTVAL, '홍길동', '안녕하세용', '냉무', 'AA@BB.COM', '111', BOARD_SEQ.CURRVAL,  0, 0, '127.0.0.1' ); -- 이메일까지는 사용자에게 받음. BGROUP, BSTEP, BINDENT는 글 타입에 따라 매겨짐.
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
VALUES (BOARD_SEQ.NEXTVAL, '신성', 'ㅂㄱ', 'ㄹㅇ', 'AA@BB.COM', '111', BOARD_SEQ.CURRVAL,  0, 0, '192.0.0.1' );
SELECT * FROM BOARD;

UPDATE board SET bemail='BB@CC.COM' WHERE BID =2;

-- DAO에 사용할 쿼리문
-- 1) 글목록 (페이징 처리. startrow부터 endrow까지의 리스트)
SELECT * FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC) ORDER BY BID DESC;
SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC) A;
SELECT *
FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC) A)
WHERE RN BETWEEN 41 AND 50;

-- 2) 전체 글 갯수
SELECT COUNT(*) CNT FROM BOARD;

-- 3) 원글쓰기 -- 작성자, 글제목, 본문, 이메일, 비밀번호, IP(FROM JAVA) 를 사용자에게 받아 게시글을 등록. (BGROUP은 글번호, BSTEP은 0, BINDENT는 0)
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
VALUES (BOARD_SEQ.NEXTVAL, '신성', 'ㅂㄱ', 'ㄹㅇ', 'AA@BB.COM', '111', BOARD_SEQ.CURRVAL,  0, 0, '192.0.0.1' );

-- 4) 글보기 - 조회수올리기 (BID 이용)
UPDATE BOARD SET BHIT = BHIT+1 WHERE BID = 1;
-- 5) 글보기 - 게시글 상세보기 (DTO 가져오기).. 4와 5를 함께 사용

-- 6) 글수정/답변글 - BID로 DTO 가져오기 (글수정FORM, 답변글FORM 이용시 사용), 조회수 올리기 사용 X
SELECT * FROM BOARD WHERE BID = 1;
-- 7) 글수정 (작성자, 글제목, 본문, 이메일, 비밀번호 수정가능)
UPDATE BOARD
SET BNAME = '홍스길스동스',
BTITLE = '바꾼제목',
BCONTENT = '바꾼본문',
BEMAIL = 'H@H.COM',
BPW = '111',
BIP = '127.0.0.1'
WHERE BID = 1;
COMMIT;
--8) 글삭제 (비밀번호를 맞게 입력한 경우에만 삭제됨)
DELETE FROM BOARD WHERE BID = 1 AND BPW = '111';
commit;
ROLLBACK;
SELECT * FROM BOARD ORDER BY BGROUP DESC;
DELETE FROM BOARD WHERE BNAME = '홍길동동' AND BID != 16;