DROP TABLE MVC_MEMBER2;
DROP SEQUENCE MVC_MEMBER2_SEQ;

CREATE TABLE MVC_MEMBER2(
    MID VARCHAR2(30) PRIMARY KEY,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MEMAIL VARCHAR2(30),
    MBIRTH DATE,
    MRDATE DATE DEFAULT SYSDATE NOT NULL
);

INSERT INTO MVC_MEMBER2 (MID, MPW, MNAME, MEMAIL, MBIRTH)
VALUES ('aaa', '111', '홍홍홍', 'aa@bb.com', '1999-09-09');

SELECT * FROM MVC_MEMBER2;

-- DAO에 들어갈 QUERY
    
-- 1. MID 중복체크
    SELECT * FROM MVC_MEMBER2 WHERE MID = 'aaa';
-- 2. 회원가입 QUERY (사진첨부X, MID, MPW, MNAME, MEMAIL, MBIRTH)
    INSERT INTO MVC_MEMBER2 (MID, MPW, MNAME, MEMAIL, MBIRTH)
VALUES ('bbb', '444', '술홍', 'aa@bb.com', '1999-09-09');
commit;
-- 3. LOGIN CHECK (MID, MPW)
    SELECT * FROM MVC_MEMBER2 WHERE MID = 'aaa' and MPW = '111';
-- 4. 로그인 성공시 SESSION에 넣을 DTO 가져오기 (MID로)
    SELECT * FROM MVC_MEMBER2 WHERE MID = 'aaa';