DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    ID VARCHAR2(30) PRIMARY KEY,
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    BIRTH DATE,
    RDATE DATE DEFAULT SYSDATE NOT NULL
);    
    
SELECT * FROM MEMBER;
INSERT INTO MEMBER (ID,PW,NAME,BIRTH)
VALUES ('AAA','1','홍길동','1999-12-12');
INSERT INTO MEMBER (ID,PW,NAME,BIRTH)
VALUES ('BBB','1','비길동','1998-01-01');
COMMIT;

-- DAO에 들어갈 QUERY
-- 회원리스트
SELECT * FROM MEMBER;
